server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Encaminha chamadas /api para o backend
    location /api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # React Router — redireciona tudo pro index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
